version: "3.7"

services:
  cors:
    build: .
    image: cors-anywhere
    container_name: cors-anywhere
    restart: always
      #ports:
         #- "8082:8082"
    networks:
      - mytestnet

networks:
  mytestnet:
    external: true

